#!/bin/bash

create_uid=${1:?'UID?'}
create_uname=${2:?'user name?'}

source `dirname $0`/../etc/setenv.bash

site_home=${SITES_BASEDIR}/${create_uname}

set -e

www_gid=`getent group ${WWW_GROUP} | cut -d ':' -f 3`

adduser --home ${site_home} --shell /bin/bash --uid ${create_uid} \
        --gecos "${TSADM_USER} ${create_uname}" --gid ${www_gid} \
        --disabled-password ${create_uname}

chmod 0751 ${site_home}

old_umask=`umask`
umask 0027

mkdir ${site_home}/.ssh
cp ${CODEDIR}/etc/ssh/authorized_keys ${site_home}/.ssh/
chown -R ${create_uname}:nobody ${site_home}/.ssh

`dirname $0`/site-env-create ${create_uname} dev

umask ${old_umask}
exit 0
