#!/bin/bash

create_uid=${1:?'UID?'}
create_uname=${2:?'user name?'}

site_home=/home/tsadm/sites/${create_uname}

set -e

www_gid=`getent group nobody | cut -d ':' -f 3`

adduser --home ${site_home} --shell /bin/bash --uid ${create_uid} \
        --gecos "TSAdm ${create_uname}" --gid ${www_gid} \
        --disabled-password ${create_uname}

chmod 0751 ${site_home}

old_umask=`umask`
umask 0027

mkdir ${site_home}/.ssh
cp /opt/dev/tsadm/etc/ssh/authorized_keys ${site_home}/.ssh/
chown -R ${create_uname}:nobody ${site_home}/.ssh

`dirname $0`/site-env-create ${create_uname} dev
#`dirname $0`/site-env-create ${create_uname} prod
#`dirname $0`/site-env-create ${create_uname} test

umask ${old_umask}
exit 0
