#!/bin/bash

PATH=/usr/sbin:/sbin:/usr/bin:/bin

create_uname=${1:?'site name?'}

if getent passwd ${create_uname}
then
    echo "${create_name} site name already exists" >&2
    exit 1
fi

set -e

source `dirname $0`/../etc/setenv.bash

repo_home=${SITES_REPO_BASEDIR}/${create_uname}
repo_path=${repo_home}/${create_uname}.git

last_uid=`grep -F 'x:61' /etc/passwd | sort -t ':' -k 3 -nr | head -n 1 | cut -d ':' -f 3`
create_uid=`expr ${last_uid} + 1`
create_gid=`getent group ${WWW_GROUP} | cut -d ':' -f 3`

old_umask=`umask`
umask 0027

# -- backups
bup_tstamp=`date '+%Y%m%d.%H%M%S'`
cat /etc/passwd | gzip -c9 - >/etc/passwd.tsadm-${bup_tstamp}.gz
cat /etc/group | gzip -c9 - >/etc/group.tsadm-${bup_tstamp}.gz
cat /etc/shadow | gzip -c9 - >/etc/shadow.tsadm-${bup_tstamp}.gz

# -- create OS user
adduser --home ${repo_home} --shell /usr/bin/git-shell \
        --uid ${create_uid} --gecos "${TSADM_USER} ${create_uname}" \
        --gid ${create_gid} --disabled-password $create_uname

# so it can execute curl command, which is used in git
# post-receive hook
adduser ${create_uname} authcmds

chmod 0750 ${repo_home}

rsync -ax ${USERS_REPO_BASEDIR}/tsadmgit/init-tmpl.git/ ${repo_path}/

echo "${create_uname} site" >${repo_path}/description

# --- SSH
mkdir ${repo_home}/.ssh
chmod 0750 ${repo_home}/.ssh
cat ${CODEDIR}/etc/ssh/authorized_keys >${repo_home}/.ssh/authorized_keys
chmod 0640 ${repo_home}/.ssh/authorized_keys

# --- Git
ln -s ${CODEDIR}/libexec/git/post-receive ${repo_path}/hooks/

chown -R ${create_uname}:${WWW_GROUP} ${repo_home}
umask ${old_umask}

echo "$(id -u ${create_uname}) ${create_uname} created"
exit 0
