#!/bin/bash

set -e

www_gid=`getent group nobody | cut -d ':' -f 3`

adduser --home /home/tsadmdev --shell /bin/bash --uid 61000 --gid $www_gid --disabled-password --disabled-login --gecos 'TSAdm' tsadmdev

adduser tsadmdev authcmds

old_umask=`umask`
umask 0027

chmod 0751 /home/tsadmdev

mkdir /home/tsadmdev/.ssh
cp /opt/tsadmdev/etc/ssh/git-server-known_hosts /home/tsadmdev/.ssh/known_hosts

mkdir /home/tsadmdev/sites
chmod 0751 /home/tsadmdev/sites

echo 'umask 0027' >>/home/tsadmdev/.bashrc

ssh-keygen -C "tsadmdev@$(hostname -s)" -f /home/tsadmdev/.ssh/id_rsa
cat /home/tsadmdev/.ssh/id_rsa.pub

chown -R tsadmdev:nobody /home/tsadmdev

umask ${old_umask}
exit 0
