#!/bin/bash

set -e
source `dirname $0`/../etc/setenv.bash

www_gid=`getent group ${WWW_GROUP} | cut -d ':' -f 3`

adduser --home ${TSADM_HOMEDIR} --shell /bin/bash --uid 61000 --gid $www_gid --disabled-password --disabled-login --gecos "${TSADM_USER}" ${TSADM_USER}

adduser ${TSADM_USER} authcmds

old_umask=`umask`
umask 0027

chmod 0751 ${TSADM_HOMEDIR}

mkdir ${TSADM_HOMEDIR}/.ssh
cp ${CODEDIR}/etc/ssh/git-server-known_hosts ${TSADM_HOMEDIR}/.ssh/known_hosts

mkdir ${SITES_BASEDIR}
chmod 0751 ${SITES_BASEDIR}

echo 'umask 0027' >>${TSADM_HOMEDIR}/.bashrc

ssh-keygen -C "${TSADM_USER}@$(hostname -s)" -f ${TSADM_HOMEDIR}/.ssh/id_rsa
cat ${TSADM_HOMEDIR}/.ssh/id_rsa.pub

chown -R ${TSADM_USER}:${WWW_GROUP} ${TSADM_HOMEDIR}

umask ${old_umask}
exit 0
