---
- hosts: localhost
  gather_facts: false
  tasks:
    - include: user.yml
    - include: jobq.yml
    - include: slave.yml
    - include: site.yml
    - include: siteenv.yml
    - include: git.yml
    - include: rsync.yml
    - include: mysql.yml
